// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Entry struct {
	ID     int64
	Date   time.Time
	Canon  int64
	Profit float64
}

type Movement struct {
	ID      int64
	EntryID int64
	Shift   string
	Amount  int64
}
