// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

type Entry struct {
	ID     uuid.UUID
	Date   time.Time
	Canon  int64
	Profit sql.NullFloat64
}

type Movement struct {
	ID      uuid.UUID
	EntryID uuid.UUID
	Shift   string
	Amount  int64
}
