// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entry (
date, canon, profit
) VALUES (
?, ?, ?
)
RETURNING id, date, canon, profit
`

type CreateEntryParams struct {
	Date   string
	Canon  int64
	Profit float64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.Date, arg.Canon, arg.Profit)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Canon,
		&i.Profit,
	)
	return i, err
}

const createMovement = `-- name: CreateMovement :exec
INSERT INTO movement (
entry_id, shift, amount
) VALUES (
?, ?, ?
)
`

type CreateMovementParams struct {
	EntryID int64
	Shift   string
	Amount  int64
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) error {
	_, err := q.db.ExecContext(ctx, createMovement, arg.EntryID, arg.Shift, arg.Amount)
	return err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, date, canon, profit
FROM entry
`

func (q *Queries) ListAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Canon,
			&i.Profit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMovements = `-- name: ListAllMovements :many
SELECT id, entry_id, shift, amount
FROM movement
`

func (q *Queries) ListAllMovements(ctx context.Context) ([]Movement, error) {
	rows, err := q.db.QueryContext(ctx, listAllMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movement
	for rows.Next() {
		var i Movement
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Shift,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
